# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
