# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_choice', '0002_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=300),
        ),
    ]
